### ISSUE TITLE
Add ability to only use lego colors

### ISSUE THREAD

**Issue by JuanPotato** [JuanPotato/Legofy#2]
Putting this here for conversation and progress

**Comment by stuaxo** [comment]
You could extract the colors from the ldraw parts library.

**Comment by Haroenv** [comment]
Good idea!

**Comment by akkatracker** [comment]
Here's a list of in use, transparent and phased out colours: http://lego.wikia.com/wiki/Colour_Palette

**Comment by wentz-s** [comment]
http://www.bricksfinder.de/lego-shop-color-list/

Just found this, maybe it will be helpful.

**Comment by RealJTG** [comment]
[LEGO releases its internal color palette (2010)](http://www.brothers-brick.com/2010/01/28/lego-releases-its-internal-color-palette-news/)

Not a big deal actually if we make legofy accept any png image as reference palette. I suggest you to start from here: http://pillow.readthedocs.org/en/3.0.x/_modules/PIL/Image.html#Image.quantize

**Comment by JuanPotato** [comment]
well, done, forgot to mention in commit
