### ISSUE TITLE
Add ability to change scale of lego peices

### ISSUE THREAD

**Issue by natemara** [JuanPotato/Legofy#27]
For example, each lego block in the output image is essentially a pixel. The user should be able to specify the new "resolution" for their image as a command line option.

**Comment by wentz-s** [comment]
Hi, you should have a look here: https://github.com/JuanPotato/Legofy/pull/24

The default scale is 30, and the higher you go, the higher the brick density (and thus, resolution of the final picture).

Here with the default scale of 30
![Scale of 30]
(http://image.noelshack.com/fichiers/2015/44/1446201651-raccoon-30.png)

Here with --scale set to 120
![Scale of 120]
(http://image.noelshack.com/fichiers/2015/44/1446201652-raccoon-120.png)

**Comment by JuanPotato** [comment]
Duplicate #13 Please continue conversation there if you need, and this is coming btw.
