### ISSUE TITLE
invalid parameter (delay) while creating gif

### ISSUE THREAD

**Issue by k1lly** [JuanPotato/Legofy#43]
Fails to create output gif with the "Finished!" message. Example `lego_rkt.gif` file isn't created in the target directory.
Here's the output message example:
![image](https://cloud.githubusercontent.com/assets/2467931/10850298/cf95537e-7f35-11e5-8a8e-3e1a90b383d2.png)

**Comment by JuanPotato** [comment]
Yeah, this is why I was planning on packaging a windows binary along with this. Sending `convert` command for imagemagick from python uses something different than when typing in the command line. You can try this by copy pasting the exact command in cmd. I'll be fixing this soon, don't worry

**Comment by JuanPotato** [comment]
This should be fixed, please try with the newest code.
