### ISSUE TITLE
Need a better 1x1 Lego Piece and 1x2 2x1

### ISSUE THREAD

**Issue by JuanPotato** [JuanPotato/Legofy#47]
BETTER ones... If anyone with photoshop knowledge could recreate a 1x1 lego piece and/or create the 2x1 and 1x2 pieces? I was hoping to have a brand new piece so that I can make sure the base color of the lego is 128,128,128

**Comment by JuanPotato** [comment]
nevermind, if I do this I know what I'll do

**Comment by symac** [comment]
@JuanPotato I was going to create an issue for this but I am seeing this one that you have closed. That would definitely be great to have a bigger image than 30px. The real size of the brick being 8mm, that means that printing the file, we have a 95PPI resolution, which is low for print, would be great to have a bigger base brick (I have tried doing an SVG one but at the moment it is not looking very realistic)

Reading your closing comment, it seems you have a solution to provide a bigger base picture, any plan to create it in the near future?

**Comment by JuanPotato** [comment]
I have a 256px one, any attempts I make at remaking a vector version of the lego results in not so realistic looking images. The 256px one should be enough, I only scaled it down for this project. I can give you the file if you would like.

**Comment by symac** [comment]
@JuanPotato can you add it to the asset folder ? I would be interested to have a try with this version. Thanks.

**Comment by JuanPotato** [comment]
@symac Soon, here
![lego](https://cloud.githubusercontent.com/assets/9531780/11674855/a52fc0a2-9df2-11e5-8324-8b89b4d32814.png)
