### ISSUE TITLE
How to run Legofy?

### ISSUE THREAD

**Issue by livibetter** [JuanPotato/Legofy#6]
Normally, when I try a new project, I don't install it, but Legofy don't seem to let me to run it directly, using 616af866ef72f1b274e4597619ee66b2f8ca6701.

Run without installation
==================

I have tried:

```bash
python legofy/__init__.py
python legofy/cli.py
python -m legofy.__init__
```

Which is expected, nothing happens as the code doesn't do anything in running this way. Do I have to install for entry point script in order to try it out?

Run after installation
================

I installed with

```bash
pip install --user .
```

But, the asset `bricks/brick.png` isn't installed:

```python
% legofy spinner.gif
Animated gif detected, will now legofy each frame and recreate the gif and save as lego_spinner.gif
Working on frame_0003.png
Traceback (most recent call last):
  File "/home/livibetter/.local/bin/legofy", line 9, in <module>
    load_entry_point('legofy==0.0.1', 'console_scripts', 'legofy')()
[snip]
  File "/home/livibetter/.local/lib64/python2.7/site-packages/legofy/__init__.py", line 54, in makeLegoBrick
    return applyEffect(Image.open(brick), colorize)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 2248, in open
    fp = builtins.open(fp, "rb")
IOError: [Errno 2] No such file or directory: '/home/livibetter/.local/lib64/python2.7/site-packages/legofy/bricks/brick.png'
```

So, I tried with `--brick`, but `here` isn't defined when run with the option, hence:

```python
% legofy --brick /tmp/Legofy/legofy/bricks/brick.png spinner.gif
Traceback (most recent call last):
  File "/home/livibetter/.local/bin/legofy", line 9, in <module>
    load_entry_point('legofy==0.0.1', 'console_scripts', 'legofy')()
[snip]
  File "/home/livibetter/.local/lib64/python2.7/site-packages/legofy/cli.py", line 13, in main
    legofy.main(image, brick=os.path.join(here, 'bricks', 'brick.png'))
UnboundLocalError: local variable 'here' referenced before assignment
```

**Comment by JuanPotato** [comment]
Once I clean up the code a bit more and remove bricks argument, I will create documentation and examples on how to use it.

**Comment by livibetter** [comment]
@JuanPotato I was thinking to draw some funky brick to see what would come out, guess it's not gonna happen.

**Comment by JuanPotato** [comment]
I'm going to keep the brick parameter (even though it's quiet useless) but
it won't be required (it currently is in code)
