### ISSUE TITLE
ValueError: --enable-zlib requested but zlib not found, aborting.

### ISSUE THREAD

**Issue by jamierocks** [JuanPotato/Legofy#68]
## /sysinfo
```
• System Information: Model: Mac Mini (Late 2014) 
• CPU: Intel Core i5-4278U (4 Threads, 2 Cores) @ 2.60 GHz 
• Memory: 8.00 GB • Uptime: 5 hours • Disk Space: 998.98 GB 
• Graphics: Intel Iris 
• Screen Resolution: 1920 x 1080 
• OS: OS X El Capitan (Version 10.11.1, Build 15B42)
```
## info
[Full log](https://gist.github.com/jamierocks/13231901e4919cc14cf4)

**Comment by JuanPotato** [comment]
just searched this up, try running `xcode-select --install` and then installing
https://github.com/python-pillow/Pillow/issues/1461

**Comment by jamierocks** [comment]
Thanks, trying that out :)

**Comment by jamierocks** [comment]
Not the same issue, but I get https://gist.github.com/jamierocks/dc5908ff01c013a27871 when legofying an image.

**Comment by JuanPotato** [comment]
@jamierocks oh I didnt see this reply, its probably a problem with out of date dependencies, I'll look it up

**Comment by jamierocks** [comment]
Awesome, thanks :)

**Comment by jamierocks** [comment]
Fixed by http://stackoverflow.com/questions/22728468/osx-pillow-incompatible-library-version-libtiff-5-dylib-libjpeg-8-dylib . Closing.
