### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by Guest007** [JuanPotato/Legofy#7]
Can't find project's description. Sorry.

**Comment by JuanPotato** [comment]
It's a program written in python that modifies gifs or still images to make them look like they were made out of legos. (I can't believe I never put a description, will do)

**Comment by JuanPotato** [comment]
Description added, a7397ed4ef23d58d952425ea32c06171f1dc3292

**Comment by nabijaczleweli** [comment]
You know you can add something along the lines of "(Fixe[sd])|(Closes) #number" to commit message, right?

**Comment by JuanPotato** [comment]
Nope, thanks @nabijaczleweli
