### ISSUE TITLE
Add description to repo

### ISSUE THREAD

**Issue by niroyb** [JuanPotato/Legofy#77]
The repo is missing a description.
![image](https://cloud.githubusercontent.com/assets/1450009/11263554/94b2897e-8e40-11e5-8b48-6db792fbcae6.png)
It would look nicer with one. Since it's not something we can do a pull request on, I'm marking it as an issue.

Could be as simple as : "Legofy images!"

**Comment by nabijaczleweli** [comment]
2/10 Needs more `!`

**Comment by niroyb** [comment]
L!E!G!O!F!Y! IM!A!G!E!S!!!! (and gifs)

**Comment by nabijaczleweli** [comment]
9/10 needs more caps

**Comment by JuanPotato** [comment]
done
