### ISSUE TITLE
Add legofy to PyPI

### ISSUE THREAD

**Issue by niroyb** [JuanPotato/Legofy#82]
[PyPI - the Python Package Index](https://pypi.python.org/pypi) would allow people to do `pip install legofy`

**Comment by JuanPotato** [comment]
but [legofy](https://pypi.python.org/pypi/legofy/) exists already :\

I have asked the owner.

**Comment by niroyb** [comment]
I don't understand why : `pip install legofy`

Outputs:
```
Collecting legofy
  Could not find a version that satisfies the requirement legofy (from versions: )
No matching distribution found for legofy
```

**Comment by JuanPotato** [comment]
@niroyb it is that way because the author probably never uploaded an actual package

it is registered if you look at the [simple](https://pypi.python.org/simple/) page, but the actual [legofy](https://pypi.python.org/simple/legofy/) entry has nothing there

**Comment by JuanPotato** [comment]
So gmail notified me that the delivery of the email failed. So I'm just going to name this package `pylegofy` or `py-legofy`

**Comment by niroyb** [comment]
I vote pylegofy.
Also bump the version number to 1.0.0

**Comment by CasualBeer** [comment]
Perhaps you should contact Foundation / PyPi Administrator ? The original owner may not even remember he/she owns it :)

**Comment by JuanPotato** [comment]
@CasualBeer I was about to do this. :D

**Comment by JuanPotato** [comment]
made the request
https://sourceforge.net/p/pypi/support-requests/562/

**Comment by oliveirarodolfo** [comment]
Have you got any feedback from sourceforge? I don't see any problem to let it go, I actually just did. But I'm really curious about the outcomes of the ticket you opened. Anyway my project had no ambition whatsoever, it was merely educational.

**Comment by JuanPotato** [comment]
@oliveirarodolfo I haven't gotten any feedback, I'll close the request, thanks again!

**Comment by oliveirarodolfo** [comment]
No pb at all! Happy coding!
