### ISSUE TITLE
Remove cli.py from coverage

### ISSUE THREAD

**Issue by niroyb** [JuanPotato/Legofy#83]
Coverage should be better.
Remove cli.py from coverage or add a test to add coverage to it.
I tried to add a test but failed to get it working with click.

**Comment by JuanPotato** [comment]
> Remove cli.py from coverage
If I knew how, I'll search up if you don't know

**Comment by JuanPotato** [comment]
I forgot to use the commit message, again. Anyway fixed

**Comment by JuanPotato** [comment]
...forgot to close it
