### ISSUE TITLE
Best way to make binary executable ?

### ISSUE THREAD

**Issue by CasualBeer** [JuanPotato/Legofy#90]
So far I always used py2exe - do you guys know better alternative that works with tkinter?

**Comment by JuanPotato** [comment]
No clue

**Comment by nabijaczleweli** [comment]
[Why](http://stackoverflow.com/questions/12339671/how-to-compile-python-script-to-binary-executable) [not](http://stackoverflow.com/questions/5458048/how-to-make-a-python-script-standalone-executable-to-run-without-any-dependency) [Google](http://stackoverflow.com/questions/2486737/convert-python-script-to-binary-executable) [it?](https://mborgerson.com/creating-an-executable-from-a-python-script)

Also, from the [first answer to first Google result](http://stackoverflow.com/a/12339729/2851815):
> Or use [PyInstaller][http://www.pyinstaller.org] as an alternative to [py2exe][http://www.py2exe.org]. Here is a good [starting point][http://www.pyinstaller.org/export/v2.0/project/doc/Manual.html?format=raw#getting-started]. PyInstaller let's you also create executables for linux and mac<sub>(sic)</sub>...

**Comment by CasualBeer** [comment]
@nabijaczleweli 

I know how Google works. I ask not because I can't use it I ask because I did and failed finding a suitable solution. Besides that there is always a hope for someone with more experience in this particular area, instead of benchmarking all of available solutions.

 Anyways, I tried pyinstaller, but have trouble setting it up probably because of tkinter,
