### ISSUE TITLE
closing image raises an error ? 

### ISSUE THREAD

**Issue by symac** [JuanPotato/Legofy#96]
Hello,
using python 2.7.6, when I run the script, I get errors in **init.py** when closing the files on :
https://github.com/JuanPotato/Legofy/blob/master/legofy/__init__.py#L177-L178

According to [this discussion](https://bytes.com/topic/python/answers/24308-pil-do-i-need-close) it seems that closing is not needed, no? Can this be removed or is there any particular reason you have done it?

**Comment by nabijaczleweli** [comment]
ヽ༼ຈل͜ຈ༽ﾉ raise your ~~dongers~~ errors ヽ༼ຈل͜ຈ༽ﾉ

**Comment by symac** [comment]
@nabijaczleweli can you tell me more? Is this issue not relevant, am I missing something?

**Comment by JuanPotato** [comment]
@symac update pillow, the travis build on 2.7 seems to be fine
